apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  namespace: actions-runner-system
  name: self-hosted-runners
spec:
  replicas: 1
  template:
    spec:
      repository: divakaivan/python-app